services:
  datacellar_provider:
    image: openjdk:17-bullseye
    container_name: datacellar_provider
    command:
      [
        "java",
        "-Dedc.hostname=datacellar_provider",
        "-Dedc.keystore=/opt/src/certs-provider/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/opt/src/certs-provider/vault.properties",
        "-Dedc.fs.config=/opt/src/provider.properties",
        "-Dedc.dsp.callback.address=http://datacellar_provider:19194/protocol",
        "-jar",
        "/opt/src/datacellar-core-connector.jar"
      ]
    ports:
      - "19291:19291"
      - "19194:19194"
    volumes:
      - .:/opt/src
    networks:
      - provider_net
networks:
  provider_net:
    name: provider_net
