$prov_script = <<-SCRIPT
apt-get update -y
apt-get install -y curl iputils-ping
curl -fsSL https://get.docker.com -o install-docker.sh
sh install-docker.sh
DOCKER_CONFIG=${DOCKER_CONFIG:-$HOME/.docker}
mkdir -p $DOCKER_CONFIG/cli-plugins
curl -SL \
    https://github.com/docker/compose/releases/download/v2.18.1/docker-compose-linux-x86_64 \
    -o $DOCKER_CONFIG/cli-plugins/docker-compose
chmod +x $DOCKER_CONFIG/cli-plugins/docker-compose
SCRIPT

unless Vagrant.has_plugin?("vagrant-reload")
  system("vagrant plugin install vagrant-reload")
end

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
    v.cpus = 1
  end

  config.vm.provision "shell", inline: $prov_script

  config.vm.define "provider", primary: true do |c|
    c.vm.hostname = "provider"
    c.vm.provision :reload
  end

  config.vm.define "consumer" do |c|
    c.vm.hostname = "consumer"
    c.vm.provision :reload
  end
end