services:
  datacellar_provider:
    image: openjdk:17-bullseye
    container_name: datacellar_provider
    command:
      [
        "java",
        "-Dedc.keystore=/opt/src/datacellar-certs/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/opt/src/datacellar-certs/vault.properties",
        "-Dedc.fs.config=/opt/src/example.properties",
        "-Dedc.dsp.callback.address=http://datacellar_provider:9194/protocol",
        "-jar",
        "/opt/src/datacellar-connector/datacellar-core-connector/build/libs/datacellar-core-connector.jar"
      ]
    ports:
      - "9194:9194"
      - "9191:9191"
      - "9193:9193"
      - "9195:9195"
      - "9291:9291"
      - "9192:9192"
    volumes:
      - .:/opt/src
