FROM python:3.10-bullseye
WORKDIR /root
COPY datacellar-certs datacellar-certs/
COPY http-pull-consumer-backend http-pull-consumer-backend/
WORKDIR /root/http-pull-consumer-backend
RUN pip install -r requirements.txt
EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]