FROM python:3.8-bullseye

ENV VENV_PATH /root/venv
ENV APP_PATH /app
ENV POETRY_VERSION=1.7.1

RUN apt-get update -y && \
    apt-get install -y --no-install-recommends avahi-utils

RUN pip install --no-cache-dir -U pip setuptools poetry==${POETRY_VERSION}

WORKDIR ${APP_PATH}
COPY . .
WORKDIR ${APP_PATH}/edcpy
RUN poetry build && pip install --no-cache-dir -U dist/*.whl