services:
  datacellar_provider:
    build:
      context: .
      dockerfile: Dockerfile.openjdk
    container_name: datacellar_provider
    restart: on-failure
    command:
      [
        "java",
        "-Dedc.hostname=provider.local",
        "-Dedc.keystore=/opt/src/example/certs-provider/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/opt/src/example/certs-provider/vault.properties",
        "-Dedc.fs.config=/opt/src/example/provider.properties",
        "-Dedc.dsp.callback.address=http://provider.local:9194/protocol",
        "-jar",
        "/opt/src/example/datacellar-core-connector.jar"
      ]
    ports:
      - "9191:9191"
      - "9193:9193"
      - "9194:9194"
      - "9291:9291"
      - "9192:9192"
    volumes:
      - .:/opt/src
      # To ensure that mDNS resolution is enabled in the container
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
