services:
  consumer:
    image: openjdk:17-bullseye
    container_name: http_push_consumer
    command:
      [
        "java",
        "-Dedc.hostname=consumer",
        "-Dedc.keystore=/certs/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/certs/vault.properties",
        "-Dedc.fs.config=/connector/datacellar-push-sample-connector/consumer.properties",
        "-Dedc.dsp.callback.address=http://consumer:29194/protocol",
        "-Dedc.receiver.http.endpoint=http://consumer_backend:8000/pull",
        "-jar",
        "/connector/datacellar-push-sample-connector/build/libs/datacellar-push-sample-connector.jar"
      ]
    ports:
      - "29194:29194"
      - "29191:29191"
      - "29193:29193"
      - "29195:29195"
      - "29291:29291"
      - "29192:29192"
    networks:
      - http_push_net
    volumes:
      - ./datacellar-connector:/connector
      - ./datacellar-certs:/certs
  provider:
    image: openjdk:17-bullseye
    container_name: http_push_provider
    command:
      [
        "java",
        "-Dedc.hostname=provider",
        "-Dedc.keystore=/certs/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/certs/vault.properties",
        "-Dedc.fs.config=/connector/datacellar-push-sample-connector/provider.properties",
        "-Dedc.dsp.callback.address=http://provider:19194/protocol",
        "-jar",
        "/connector/datacellar-push-sample-connector/build/libs/datacellar-push-sample-connector.jar"
      ]
    ports:
      - "19194:19194"
      - "19191:19191"
      - "19193:19193"
      - "19195:19195"
      - "19291:19291"
      - "19192:19192"
    networks:
      - http_push_net
    volumes:
      - ./datacellar-connector:/connector
      - ./datacellar-certs:/certs
  consumer_backend:
    build:
      dockerfile: Dockerfile.edcpy
    container_name: http_push_consumer_backend
    command: [ "run-http-backend" ]
    environment:
      PORT: 8000
    ports:
      - "8000:8000"
    networks:
      - http_push_net
networks:
  http_push_net:
    name: ${HTTP_PUSH_NETWORK:-edc_http_push}
