services:
  provider:
    build: .
    image: edc-connector
    pull_policy: never
    container_name: provider
    restart: on-failure
    ports:
      - 19191:19191
      - 19193:19193
      - 19194:19194
      - 19291:19291
      - 19192:19192
    environment:
      PROPERTIES_FILE_PATH: /opt/src/dev-config/dev-provider.properties
      KEYSTORE_PATH: /opt/src/dev-config/certs-provider/cert.pfx
      KEYSTORE_PASSWORD: datacellar
    volumes:
      - .:/opt/src
