services:
  datacellar_consumer:
    build:
      context: .
      dockerfile: Dockerfile.openjdk
    container_name: datacellar_consumer
    restart: on-failure
    command:
      [
        "java",
        "-Dedc.hostname=consumer.local",
        "-Dedc.keystore=/opt/src/example/certs-consumer/cert.pfx",
        "-Dedc.keystore.password=datacellar",
        "-Dedc.vault=/opt/src/example/certs-consumer/vault.properties",
        "-Dedc.fs.config=/opt/src/example/consumer.properties",
        "-Dedc.dsp.callback.address=http://consumer.local:9194/protocol",
        "-jar",
        "/opt/src/example/datacellar-core-connector.jar"
      ]
    ports:
      - "9191:9191"
      - "9193:9193"
      - "9194:9194"
      - "9291:9291"
      - "9192:9192"
    volumes:
      - .:/opt/src
      # To ensure that mDNS resolution is enabled in the container
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
  datacellar_consumer_backend:
    build:
      context: .
      dockerfile: Dockerfile.edcpy
    container_name: datacellar_consumer_backend
    restart: on-failure
    command: [ "run-http-backend" ]
    volumes:
      - .:/opt/src
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      EDC_CERT_PATH: /opt/src/example/certs-consumer/cert.pem
      EDC_RABBIT_URL: "amqp://guest:guest@broker:5672"
      EDC_HTTP_API_PORT: 8000
    ports:
      - "8000:8000"
  datacellar_consumer_sandbox:
    build:
      context: .
      dockerfile: Dockerfile.edcpy
    container_name: datacellar_consumer_sandbox
    restart: on-failure
    command: [ "sleep", "infinity" ]
    volumes:
      - .:/opt/src
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    environment:
      EDC_CERT_PATH: /opt/src/example/certs-consumer/cert.pem
      EDC_RABBIT_URL: "amqp://guest:guest@broker:5672"
    env_file: ./example/.env.example
  broker:
    image: rabbitmq:3.11
    container_name: datacellar_consumer_broker
    restart: on-failure
    ports:
      - "5672:5672"
