services:
  http_api:
    build: .
    container_name: mock_backend_http_api
    pull_policy: never
    command: ["uvicorn", "http-api:app", "--host", "0.0.0.0", "--port", "9090"]
    restart: on-failure
    environment:
      ENABLE_PRESENTATION_DEFINITION: ${ENABLE_PRESENTATION_DEFINITION:-}
    ports:
      - "9090:9090"
