/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package datacellar.connector.app;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class DummyTest {
    @Test
    void testDummy() {
        assertEquals(true, true);
    }
}
