name: Publish core connector image

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and push the connector image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: Login to Docker Hub
        uses: docker/login-action@v2.2.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (OAuth2 enabled)
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: |
            ENABLE_OAUTH2=true
          tags: |
            agmangas/edc-connector:latest
            agmangas/edc-connector:${{ github.ref_name }}
            agmangas/edc-connector:${{ github.sha }}
      - name: Build and push (OAuth2 disabled)
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          build-args: |
            ENABLE_OAUTH2=false
          tags: |
            agmangas/edc-connector:latest-oauth2
            agmangas/edc-connector:${{ github.ref_name }}-oauth2
            agmangas/edc-connector:${{ github.sha }}-oauth2
