name: Publish core connector image

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: agmangas/edc-connector

jobs:
  build-push:
    name: Build and push the connector image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (Mock identity)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ENABLE_OAUTH2=false
            ENABLE_SSI=false
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
      - name: Build and push (OAuth2 identity)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ENABLE_OAUTH2=true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-oauth2
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-oauth2
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-oauth2
      - name: Build and push (SSI identity)
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          build-args: |
            ENABLE_SSI=true
          tags: |
            ${{ env.IMAGE_NAME }}:latest-ssi
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}-ssi
            ${{ env.IMAGE_NAME }}:${{ github.sha }}-ssi
